apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 547217749840.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 547217749840.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: 236d48ed
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
